version: 3.6.{build}
image: Visual Studio 2019
before_build:
   - nuget restore
build:
  project: LaunchDarkly.Api.csproj
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 5lChoKhvR/kB2A5y4hkX08iFbEeWbWAYHykdl1kVZwPc2iCL4aBayAvJqCKYmYCZ
  skip_symbols: true
