name: .NET Build and NuGet Publish
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Restore dependencies
        run: nuget restore $SOLUTION
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_TOKEN}}
